import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import AboutUs from '../components/AboutUs'
import MastHead from '../components/Masthead'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>KlerKpn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MastHead />
      <AboutUs />
    </div>
  )
}

export default Home
